//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zadatak10WebApp.SVCKursnaLista {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SVCKursnaLista.KursnaListaSoap")]
    public interface KursnaListaSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Zadatak10WebApp.SVCKursnaLista.HelloWorldResponse HelloWorld(Zadatak10WebApp.SVCKursnaLista.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Zadatak10WebApp.SVCKursnaLista.HelloWorldResponse> HelloWorldAsync(Zadatak10WebApp.SVCKursnaLista.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name valuta from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProcitajKursNaDan", ReplyAction="*")]
        Zadatak10WebApp.SVCKursnaLista.ProcitajKursNaDanResponse ProcitajKursNaDan(Zadatak10WebApp.SVCKursnaLista.ProcitajKursNaDanRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProcitajKursNaDan", ReplyAction="*")]
        System.Threading.Tasks.Task<Zadatak10WebApp.SVCKursnaLista.ProcitajKursNaDanResponse> ProcitajKursNaDanAsync(Zadatak10WebApp.SVCKursnaLista.ProcitajKursNaDanRequest request);
        
        // CODEGEN: Generating message contract since element name valuta from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpisiKursNaDan", ReplyAction="*")]
        Zadatak10WebApp.SVCKursnaLista.UpisiKursNaDanResponse UpisiKursNaDan(Zadatak10WebApp.SVCKursnaLista.UpisiKursNaDanRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpisiKursNaDan", ReplyAction="*")]
        System.Threading.Tasks.Task<Zadatak10WebApp.SVCKursnaLista.UpisiKursNaDanResponse> UpisiKursNaDanAsync(Zadatak10WebApp.SVCKursnaLista.UpisiKursNaDanRequest request);
        
        // CODEGEN: Generating message contract since element name ProcitajSveValuteResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProcitajSveValute", ReplyAction="*")]
        Zadatak10WebApp.SVCKursnaLista.ProcitajSveValuteResponse ProcitajSveValute(Zadatak10WebApp.SVCKursnaLista.ProcitajSveValuteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProcitajSveValute", ReplyAction="*")]
        System.Threading.Tasks.Task<Zadatak10WebApp.SVCKursnaLista.ProcitajSveValuteResponse> ProcitajSveValuteAsync(Zadatak10WebApp.SVCKursnaLista.ProcitajSveValuteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Zadatak10WebApp.SVCKursnaLista.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Zadatak10WebApp.SVCKursnaLista.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Zadatak10WebApp.SVCKursnaLista.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Zadatak10WebApp.SVCKursnaLista.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcitajKursNaDanRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcitajKursNaDan", Namespace="http://tempuri.org/", Order=0)]
        public Zadatak10WebApp.SVCKursnaLista.ProcitajKursNaDanRequestBody Body;
        
        public ProcitajKursNaDanRequest() {
        }
        
        public ProcitajKursNaDanRequest(Zadatak10WebApp.SVCKursnaLista.ProcitajKursNaDanRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ProcitajKursNaDanRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime Datum;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string valuta;
        
        public ProcitajKursNaDanRequestBody() {
        }
        
        public ProcitajKursNaDanRequestBody(System.DateTime Datum, string valuta) {
            this.Datum = Datum;
            this.valuta = valuta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcitajKursNaDanResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcitajKursNaDanResponse", Namespace="http://tempuri.org/", Order=0)]
        public Zadatak10WebApp.SVCKursnaLista.ProcitajKursNaDanResponseBody Body;
        
        public ProcitajKursNaDanResponse() {
        }
        
        public ProcitajKursNaDanResponse(Zadatak10WebApp.SVCKursnaLista.ProcitajKursNaDanResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ProcitajKursNaDanResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public decimal ProcitajKursNaDanResult;
        
        public ProcitajKursNaDanResponseBody() {
        }
        
        public ProcitajKursNaDanResponseBody(decimal ProcitajKursNaDanResult) {
            this.ProcitajKursNaDanResult = ProcitajKursNaDanResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpisiKursNaDanRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpisiKursNaDan", Namespace="http://tempuri.org/", Order=0)]
        public Zadatak10WebApp.SVCKursnaLista.UpisiKursNaDanRequestBody Body;
        
        public UpisiKursNaDanRequest() {
        }
        
        public UpisiKursNaDanRequest(Zadatak10WebApp.SVCKursnaLista.UpisiKursNaDanRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpisiKursNaDanRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime datum;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string valuta;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public decimal kurs;
        
        public UpisiKursNaDanRequestBody() {
        }
        
        public UpisiKursNaDanRequestBody(System.DateTime datum, string valuta, decimal kurs) {
            this.datum = datum;
            this.valuta = valuta;
            this.kurs = kurs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpisiKursNaDanResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpisiKursNaDanResponse", Namespace="http://tempuri.org/", Order=0)]
        public Zadatak10WebApp.SVCKursnaLista.UpisiKursNaDanResponseBody Body;
        
        public UpisiKursNaDanResponse() {
        }
        
        public UpisiKursNaDanResponse(Zadatak10WebApp.SVCKursnaLista.UpisiKursNaDanResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpisiKursNaDanResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpisiKursNaDanResult;
        
        public UpisiKursNaDanResponseBody() {
        }
        
        public UpisiKursNaDanResponseBody(bool UpisiKursNaDanResult) {
            this.UpisiKursNaDanResult = UpisiKursNaDanResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcitajSveValuteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcitajSveValute", Namespace="http://tempuri.org/", Order=0)]
        public Zadatak10WebApp.SVCKursnaLista.ProcitajSveValuteRequestBody Body;
        
        public ProcitajSveValuteRequest() {
        }
        
        public ProcitajSveValuteRequest(Zadatak10WebApp.SVCKursnaLista.ProcitajSveValuteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ProcitajSveValuteRequestBody {
        
        public ProcitajSveValuteRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcitajSveValuteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcitajSveValuteResponse", Namespace="http://tempuri.org/", Order=0)]
        public Zadatak10WebApp.SVCKursnaLista.ProcitajSveValuteResponseBody Body;
        
        public ProcitajSveValuteResponse() {
        }
        
        public ProcitajSveValuteResponse(Zadatak10WebApp.SVCKursnaLista.ProcitajSveValuteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ProcitajSveValuteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Zadatak10WebApp.SVCKursnaLista.ArrayOfString ProcitajSveValuteResult;
        
        public ProcitajSveValuteResponseBody() {
        }
        
        public ProcitajSveValuteResponseBody(Zadatak10WebApp.SVCKursnaLista.ArrayOfString ProcitajSveValuteResult) {
            this.ProcitajSveValuteResult = ProcitajSveValuteResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface KursnaListaSoapChannel : Zadatak10WebApp.SVCKursnaLista.KursnaListaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KursnaListaSoapClient : System.ServiceModel.ClientBase<Zadatak10WebApp.SVCKursnaLista.KursnaListaSoap>, Zadatak10WebApp.SVCKursnaLista.KursnaListaSoap {
        
        public KursnaListaSoapClient() {
        }
        
        public KursnaListaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KursnaListaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KursnaListaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KursnaListaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Zadatak10WebApp.SVCKursnaLista.HelloWorldResponse Zadatak10WebApp.SVCKursnaLista.KursnaListaSoap.HelloWorld(Zadatak10WebApp.SVCKursnaLista.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Zadatak10WebApp.SVCKursnaLista.HelloWorldRequest inValue = new Zadatak10WebApp.SVCKursnaLista.HelloWorldRequest();
            inValue.Body = new Zadatak10WebApp.SVCKursnaLista.HelloWorldRequestBody();
            Zadatak10WebApp.SVCKursnaLista.HelloWorldResponse retVal = ((Zadatak10WebApp.SVCKursnaLista.KursnaListaSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Zadatak10WebApp.SVCKursnaLista.HelloWorldResponse> Zadatak10WebApp.SVCKursnaLista.KursnaListaSoap.HelloWorldAsync(Zadatak10WebApp.SVCKursnaLista.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Zadatak10WebApp.SVCKursnaLista.HelloWorldResponse> HelloWorldAsync() {
            Zadatak10WebApp.SVCKursnaLista.HelloWorldRequest inValue = new Zadatak10WebApp.SVCKursnaLista.HelloWorldRequest();
            inValue.Body = new Zadatak10WebApp.SVCKursnaLista.HelloWorldRequestBody();
            return ((Zadatak10WebApp.SVCKursnaLista.KursnaListaSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Zadatak10WebApp.SVCKursnaLista.ProcitajKursNaDanResponse Zadatak10WebApp.SVCKursnaLista.KursnaListaSoap.ProcitajKursNaDan(Zadatak10WebApp.SVCKursnaLista.ProcitajKursNaDanRequest request) {
            return base.Channel.ProcitajKursNaDan(request);
        }
        
        public decimal ProcitajKursNaDan(System.DateTime Datum, string valuta) {
            Zadatak10WebApp.SVCKursnaLista.ProcitajKursNaDanRequest inValue = new Zadatak10WebApp.SVCKursnaLista.ProcitajKursNaDanRequest();
            inValue.Body = new Zadatak10WebApp.SVCKursnaLista.ProcitajKursNaDanRequestBody();
            inValue.Body.Datum = Datum;
            inValue.Body.valuta = valuta;
            Zadatak10WebApp.SVCKursnaLista.ProcitajKursNaDanResponse retVal = ((Zadatak10WebApp.SVCKursnaLista.KursnaListaSoap)(this)).ProcitajKursNaDan(inValue);
            return retVal.Body.ProcitajKursNaDanResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Zadatak10WebApp.SVCKursnaLista.ProcitajKursNaDanResponse> Zadatak10WebApp.SVCKursnaLista.KursnaListaSoap.ProcitajKursNaDanAsync(Zadatak10WebApp.SVCKursnaLista.ProcitajKursNaDanRequest request) {
            return base.Channel.ProcitajKursNaDanAsync(request);
        }
        
        public System.Threading.Tasks.Task<Zadatak10WebApp.SVCKursnaLista.ProcitajKursNaDanResponse> ProcitajKursNaDanAsync(System.DateTime Datum, string valuta) {
            Zadatak10WebApp.SVCKursnaLista.ProcitajKursNaDanRequest inValue = new Zadatak10WebApp.SVCKursnaLista.ProcitajKursNaDanRequest();
            inValue.Body = new Zadatak10WebApp.SVCKursnaLista.ProcitajKursNaDanRequestBody();
            inValue.Body.Datum = Datum;
            inValue.Body.valuta = valuta;
            return ((Zadatak10WebApp.SVCKursnaLista.KursnaListaSoap)(this)).ProcitajKursNaDanAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Zadatak10WebApp.SVCKursnaLista.UpisiKursNaDanResponse Zadatak10WebApp.SVCKursnaLista.KursnaListaSoap.UpisiKursNaDan(Zadatak10WebApp.SVCKursnaLista.UpisiKursNaDanRequest request) {
            return base.Channel.UpisiKursNaDan(request);
        }
        
        public bool UpisiKursNaDan(System.DateTime datum, string valuta, decimal kurs) {
            Zadatak10WebApp.SVCKursnaLista.UpisiKursNaDanRequest inValue = new Zadatak10WebApp.SVCKursnaLista.UpisiKursNaDanRequest();
            inValue.Body = new Zadatak10WebApp.SVCKursnaLista.UpisiKursNaDanRequestBody();
            inValue.Body.datum = datum;
            inValue.Body.valuta = valuta;
            inValue.Body.kurs = kurs;
            Zadatak10WebApp.SVCKursnaLista.UpisiKursNaDanResponse retVal = ((Zadatak10WebApp.SVCKursnaLista.KursnaListaSoap)(this)).UpisiKursNaDan(inValue);
            return retVal.Body.UpisiKursNaDanResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Zadatak10WebApp.SVCKursnaLista.UpisiKursNaDanResponse> Zadatak10WebApp.SVCKursnaLista.KursnaListaSoap.UpisiKursNaDanAsync(Zadatak10WebApp.SVCKursnaLista.UpisiKursNaDanRequest request) {
            return base.Channel.UpisiKursNaDanAsync(request);
        }
        
        public System.Threading.Tasks.Task<Zadatak10WebApp.SVCKursnaLista.UpisiKursNaDanResponse> UpisiKursNaDanAsync(System.DateTime datum, string valuta, decimal kurs) {
            Zadatak10WebApp.SVCKursnaLista.UpisiKursNaDanRequest inValue = new Zadatak10WebApp.SVCKursnaLista.UpisiKursNaDanRequest();
            inValue.Body = new Zadatak10WebApp.SVCKursnaLista.UpisiKursNaDanRequestBody();
            inValue.Body.datum = datum;
            inValue.Body.valuta = valuta;
            inValue.Body.kurs = kurs;
            return ((Zadatak10WebApp.SVCKursnaLista.KursnaListaSoap)(this)).UpisiKursNaDanAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Zadatak10WebApp.SVCKursnaLista.ProcitajSveValuteResponse Zadatak10WebApp.SVCKursnaLista.KursnaListaSoap.ProcitajSveValute(Zadatak10WebApp.SVCKursnaLista.ProcitajSveValuteRequest request) {
            return base.Channel.ProcitajSveValute(request);
        }
        
        public Zadatak10WebApp.SVCKursnaLista.ArrayOfString ProcitajSveValute() {
            Zadatak10WebApp.SVCKursnaLista.ProcitajSveValuteRequest inValue = new Zadatak10WebApp.SVCKursnaLista.ProcitajSveValuteRequest();
            inValue.Body = new Zadatak10WebApp.SVCKursnaLista.ProcitajSveValuteRequestBody();
            Zadatak10WebApp.SVCKursnaLista.ProcitajSveValuteResponse retVal = ((Zadatak10WebApp.SVCKursnaLista.KursnaListaSoap)(this)).ProcitajSveValute(inValue);
            return retVal.Body.ProcitajSveValuteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Zadatak10WebApp.SVCKursnaLista.ProcitajSveValuteResponse> Zadatak10WebApp.SVCKursnaLista.KursnaListaSoap.ProcitajSveValuteAsync(Zadatak10WebApp.SVCKursnaLista.ProcitajSveValuteRequest request) {
            return base.Channel.ProcitajSveValuteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Zadatak10WebApp.SVCKursnaLista.ProcitajSveValuteResponse> ProcitajSveValuteAsync() {
            Zadatak10WebApp.SVCKursnaLista.ProcitajSveValuteRequest inValue = new Zadatak10WebApp.SVCKursnaLista.ProcitajSveValuteRequest();
            inValue.Body = new Zadatak10WebApp.SVCKursnaLista.ProcitajSveValuteRequestBody();
            return ((Zadatak10WebApp.SVCKursnaLista.KursnaListaSoap)(this)).ProcitajSveValuteAsync(inValue);
        }
    }
}
