//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zadatak9WebApp.ServiceKonvertorTeksta {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceKonvertorTeksta.KonvertorTekstaSoap")]
    public interface KonvertorTekstaSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Zadatak9WebApp.ServiceKonvertorTeksta.HelloWorldResponse HelloWorld(Zadatak9WebApp.ServiceKonvertorTeksta.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Zadatak9WebApp.ServiceKonvertorTeksta.HelloWorldResponse> HelloWorldAsync(Zadatak9WebApp.ServiceKonvertorTeksta.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name tekst from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CirilicaULatinicu", ReplyAction="*")]
        Zadatak9WebApp.ServiceKonvertorTeksta.CirilicaULatinicuResponse CirilicaULatinicu(Zadatak9WebApp.ServiceKonvertorTeksta.CirilicaULatinicuRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CirilicaULatinicu", ReplyAction="*")]
        System.Threading.Tasks.Task<Zadatak9WebApp.ServiceKonvertorTeksta.CirilicaULatinicuResponse> CirilicaULatinicuAsync(Zadatak9WebApp.ServiceKonvertorTeksta.CirilicaULatinicuRequest request);
        
        // CODEGEN: Generating message contract since element name tekst from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LatinicaUCirilicu", ReplyAction="*")]
        Zadatak9WebApp.ServiceKonvertorTeksta.LatinicaUCirilicuResponse LatinicaUCirilicu(Zadatak9WebApp.ServiceKonvertorTeksta.LatinicaUCirilicuRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LatinicaUCirilicu", ReplyAction="*")]
        System.Threading.Tasks.Task<Zadatak9WebApp.ServiceKonvertorTeksta.LatinicaUCirilicuResponse> LatinicaUCirilicuAsync(Zadatak9WebApp.ServiceKonvertorTeksta.LatinicaUCirilicuRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Zadatak9WebApp.ServiceKonvertorTeksta.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Zadatak9WebApp.ServiceKonvertorTeksta.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Zadatak9WebApp.ServiceKonvertorTeksta.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Zadatak9WebApp.ServiceKonvertorTeksta.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CirilicaULatinicuRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CirilicaULatinicu", Namespace="http://tempuri.org/", Order=0)]
        public Zadatak9WebApp.ServiceKonvertorTeksta.CirilicaULatinicuRequestBody Body;
        
        public CirilicaULatinicuRequest() {
        }
        
        public CirilicaULatinicuRequest(Zadatak9WebApp.ServiceKonvertorTeksta.CirilicaULatinicuRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CirilicaULatinicuRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string tekst;
        
        public CirilicaULatinicuRequestBody() {
        }
        
        public CirilicaULatinicuRequestBody(string tekst) {
            this.tekst = tekst;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CirilicaULatinicuResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CirilicaULatinicuResponse", Namespace="http://tempuri.org/", Order=0)]
        public Zadatak9WebApp.ServiceKonvertorTeksta.CirilicaULatinicuResponseBody Body;
        
        public CirilicaULatinicuResponse() {
        }
        
        public CirilicaULatinicuResponse(Zadatak9WebApp.ServiceKonvertorTeksta.CirilicaULatinicuResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CirilicaULatinicuResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CirilicaULatinicuResult;
        
        public CirilicaULatinicuResponseBody() {
        }
        
        public CirilicaULatinicuResponseBody(string CirilicaULatinicuResult) {
            this.CirilicaULatinicuResult = CirilicaULatinicuResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LatinicaUCirilicuRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LatinicaUCirilicu", Namespace="http://tempuri.org/", Order=0)]
        public Zadatak9WebApp.ServiceKonvertorTeksta.LatinicaUCirilicuRequestBody Body;
        
        public LatinicaUCirilicuRequest() {
        }
        
        public LatinicaUCirilicuRequest(Zadatak9WebApp.ServiceKonvertorTeksta.LatinicaUCirilicuRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LatinicaUCirilicuRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string tekst;
        
        public LatinicaUCirilicuRequestBody() {
        }
        
        public LatinicaUCirilicuRequestBody(string tekst) {
            this.tekst = tekst;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LatinicaUCirilicuResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LatinicaUCirilicuResponse", Namespace="http://tempuri.org/", Order=0)]
        public Zadatak9WebApp.ServiceKonvertorTeksta.LatinicaUCirilicuResponseBody Body;
        
        public LatinicaUCirilicuResponse() {
        }
        
        public LatinicaUCirilicuResponse(Zadatak9WebApp.ServiceKonvertorTeksta.LatinicaUCirilicuResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LatinicaUCirilicuResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LatinicaUCirilicuResult;
        
        public LatinicaUCirilicuResponseBody() {
        }
        
        public LatinicaUCirilicuResponseBody(string LatinicaUCirilicuResult) {
            this.LatinicaUCirilicuResult = LatinicaUCirilicuResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface KonvertorTekstaSoapChannel : Zadatak9WebApp.ServiceKonvertorTeksta.KonvertorTekstaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KonvertorTekstaSoapClient : System.ServiceModel.ClientBase<Zadatak9WebApp.ServiceKonvertorTeksta.KonvertorTekstaSoap>, Zadatak9WebApp.ServiceKonvertorTeksta.KonvertorTekstaSoap {
        
        public KonvertorTekstaSoapClient() {
        }
        
        public KonvertorTekstaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KonvertorTekstaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KonvertorTekstaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KonvertorTekstaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Zadatak9WebApp.ServiceKonvertorTeksta.HelloWorldResponse Zadatak9WebApp.ServiceKonvertorTeksta.KonvertorTekstaSoap.HelloWorld(Zadatak9WebApp.ServiceKonvertorTeksta.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Zadatak9WebApp.ServiceKonvertorTeksta.HelloWorldRequest inValue = new Zadatak9WebApp.ServiceKonvertorTeksta.HelloWorldRequest();
            inValue.Body = new Zadatak9WebApp.ServiceKonvertorTeksta.HelloWorldRequestBody();
            Zadatak9WebApp.ServiceKonvertorTeksta.HelloWorldResponse retVal = ((Zadatak9WebApp.ServiceKonvertorTeksta.KonvertorTekstaSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Zadatak9WebApp.ServiceKonvertorTeksta.HelloWorldResponse> Zadatak9WebApp.ServiceKonvertorTeksta.KonvertorTekstaSoap.HelloWorldAsync(Zadatak9WebApp.ServiceKonvertorTeksta.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Zadatak9WebApp.ServiceKonvertorTeksta.HelloWorldResponse> HelloWorldAsync() {
            Zadatak9WebApp.ServiceKonvertorTeksta.HelloWorldRequest inValue = new Zadatak9WebApp.ServiceKonvertorTeksta.HelloWorldRequest();
            inValue.Body = new Zadatak9WebApp.ServiceKonvertorTeksta.HelloWorldRequestBody();
            return ((Zadatak9WebApp.ServiceKonvertorTeksta.KonvertorTekstaSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Zadatak9WebApp.ServiceKonvertorTeksta.CirilicaULatinicuResponse Zadatak9WebApp.ServiceKonvertorTeksta.KonvertorTekstaSoap.CirilicaULatinicu(Zadatak9WebApp.ServiceKonvertorTeksta.CirilicaULatinicuRequest request) {
            return base.Channel.CirilicaULatinicu(request);
        }
        
        public string CirilicaULatinicu(string tekst) {
            Zadatak9WebApp.ServiceKonvertorTeksta.CirilicaULatinicuRequest inValue = new Zadatak9WebApp.ServiceKonvertorTeksta.CirilicaULatinicuRequest();
            inValue.Body = new Zadatak9WebApp.ServiceKonvertorTeksta.CirilicaULatinicuRequestBody();
            inValue.Body.tekst = tekst;
            Zadatak9WebApp.ServiceKonvertorTeksta.CirilicaULatinicuResponse retVal = ((Zadatak9WebApp.ServiceKonvertorTeksta.KonvertorTekstaSoap)(this)).CirilicaULatinicu(inValue);
            return retVal.Body.CirilicaULatinicuResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Zadatak9WebApp.ServiceKonvertorTeksta.CirilicaULatinicuResponse> Zadatak9WebApp.ServiceKonvertorTeksta.KonvertorTekstaSoap.CirilicaULatinicuAsync(Zadatak9WebApp.ServiceKonvertorTeksta.CirilicaULatinicuRequest request) {
            return base.Channel.CirilicaULatinicuAsync(request);
        }
        
        public System.Threading.Tasks.Task<Zadatak9WebApp.ServiceKonvertorTeksta.CirilicaULatinicuResponse> CirilicaULatinicuAsync(string tekst) {
            Zadatak9WebApp.ServiceKonvertorTeksta.CirilicaULatinicuRequest inValue = new Zadatak9WebApp.ServiceKonvertorTeksta.CirilicaULatinicuRequest();
            inValue.Body = new Zadatak9WebApp.ServiceKonvertorTeksta.CirilicaULatinicuRequestBody();
            inValue.Body.tekst = tekst;
            return ((Zadatak9WebApp.ServiceKonvertorTeksta.KonvertorTekstaSoap)(this)).CirilicaULatinicuAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Zadatak9WebApp.ServiceKonvertorTeksta.LatinicaUCirilicuResponse Zadatak9WebApp.ServiceKonvertorTeksta.KonvertorTekstaSoap.LatinicaUCirilicu(Zadatak9WebApp.ServiceKonvertorTeksta.LatinicaUCirilicuRequest request) {
            return base.Channel.LatinicaUCirilicu(request);
        }
        
        public string LatinicaUCirilicu(string tekst) {
            Zadatak9WebApp.ServiceKonvertorTeksta.LatinicaUCirilicuRequest inValue = new Zadatak9WebApp.ServiceKonvertorTeksta.LatinicaUCirilicuRequest();
            inValue.Body = new Zadatak9WebApp.ServiceKonvertorTeksta.LatinicaUCirilicuRequestBody();
            inValue.Body.tekst = tekst;
            Zadatak9WebApp.ServiceKonvertorTeksta.LatinicaUCirilicuResponse retVal = ((Zadatak9WebApp.ServiceKonvertorTeksta.KonvertorTekstaSoap)(this)).LatinicaUCirilicu(inValue);
            return retVal.Body.LatinicaUCirilicuResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Zadatak9WebApp.ServiceKonvertorTeksta.LatinicaUCirilicuResponse> Zadatak9WebApp.ServiceKonvertorTeksta.KonvertorTekstaSoap.LatinicaUCirilicuAsync(Zadatak9WebApp.ServiceKonvertorTeksta.LatinicaUCirilicuRequest request) {
            return base.Channel.LatinicaUCirilicuAsync(request);
        }
        
        public System.Threading.Tasks.Task<Zadatak9WebApp.ServiceKonvertorTeksta.LatinicaUCirilicuResponse> LatinicaUCirilicuAsync(string tekst) {
            Zadatak9WebApp.ServiceKonvertorTeksta.LatinicaUCirilicuRequest inValue = new Zadatak9WebApp.ServiceKonvertorTeksta.LatinicaUCirilicuRequest();
            inValue.Body = new Zadatak9WebApp.ServiceKonvertorTeksta.LatinicaUCirilicuRequestBody();
            inValue.Body.tekst = tekst;
            return ((Zadatak9WebApp.ServiceKonvertorTeksta.KonvertorTekstaSoap)(this)).LatinicaUCirilicuAsync(inValue);
        }
    }
}
